name: CI
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'A tag para as imagens Docker (ex: v1.0.0)'
        required: true
        default: 'latest'
  # Aciona a pipeline quando uma tag no formato v*.*.* é criada
  push:
    tags:
      - 'v*.*.*'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Extrair tag para versionamento da API
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: omatheusdocker/prj-to-do-api
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=true

      - name: Extrair tag para versionamento do App
        id: meta-app
        uses: docker/metadata-action@v5
        with:
          images: omatheusdocker/prj-to-do-app
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=true

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build e Push da imagem da API
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

      - name: Build e Push da imagem do App
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}
