name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  CI:
    runs-on: ubuntu-latest
    outputs:
      # Expõe a versão extraída para que outros jobs possam usá-la
      version: ${{ steps.meta-api.outputs.version }}
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Extrair metadados (tags e labels) para a API
        id: meta-api
        uses: docker/metadata-action@v5
        with:
          images: omatheusdocker/prj-to-do-api
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=true

      - name: Extrair metadados (tags e labels) para o App
        id: meta-app
        uses: docker/metadata-action@v5
        with:
          images: omatheusdocker/prj-to-do-app
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable=true

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build e Push da imagem da API
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}

      - name: Build e Push da imagem do App
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar contexto do Kubernetes
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy no cluster Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
          # Substitui as imagens nos manifestos usando a versão passada pelo job CI
          images: |
            omatheusdocker/prj-to-do-api:${{ needs.CI.outputs.version }}
            omatheusdocker/prj-to-do-app:${{ needs.CI.outputs.version }}